version: "3"

services:
  android-service:
    image: android-emulator
    command: ./start_emu_headless.sh && ./start_appium.sh
    ports:
      - 4723:4723
    privileged: true
    tty: true
    stdin_open: true

  # vnc-service:
  #   image: android-emulator
  #   command: ./start_vnc.sh
  #   environment: 
  #     VNC_PASSWORD: password
  #   ports:
  #     - 5900:5900
  #   privileged: true
  #   tty: true
  #   stdin_open: true
